#!/usr/bin/env bash
# 生成本地 agent_secrets.h（不提交 git）。
# 优先级：secrets/agent_llm.key > 环境变量 MIMO_API_KEY > 空 key。
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CONTEST_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
OUT="$CONTEST_ROOT/app/velaguard/agent_secrets.h"
KEY_FILE="$CONTEST_ROOT/secrets/agent_llm.key"

KEY=""
if [[ -f "$KEY_FILE" ]]; then
  KEY="$(tr -d '\r\n' < "$KEY_FILE")"
elif [[ -n "${MIMO_API_KEY:-}" ]]; then
  KEY="$MIMO_API_KEY"
fi

python3 - "$OUT" "$KEY" <<'PY'
import sys

out_path, key = sys.argv[1], sys.argv[2]

def c_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')

body = f"""/* Generated by scripts/gen-agent-secrets.sh — do not commit. */
#ifndef __VG_AGENT_SECRETS_H
#define __VG_AGENT_SECRETS_H

#define VG_AGENT_LLM_HOST "token-plan-cn.xiaomimimo.com"
#define VG_AGENT_LLM_PATH "/v1/chat/completions"
#define VG_AGENT_LLM_PORT "443"
#define VG_AGENT_LLM_MODEL "mimo-v2.5"
#define VG_AGENT_LLM_API_KEY "{c_escape(key)}"

#endif
"""

with open(out_path, "w", encoding="utf-8", newline="\n") as f:
    f.write(body)
PY

if [[ -n "$KEY" ]]; then
  echo "[gen-agent-secrets] wrote $OUT (api_key len=${#KEY})"
else
  echo "[gen-agent-secrets] wrote $OUT (api_key empty — add secrets/agent_llm.key or MIMO_API_KEY)"
fi
