############################################################################
# Team Falcons VS Code Lab - Makefile
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = vscode_lab
PRIORITY  = $(CONFIG_LVX_USE_DEMO_CONTEST2026_004_VSCODE_LAB_PRIORITY)
STACKSIZE = $(CONFIG_LVX_USE_DEMO_CONTEST2026_004_VSCODE_LAB_STACKSIZE)
MODULE    = $(CONFIG_LVX_USE_DEMO_CONTEST2026_004_VSCODE_LAB)

MAINSRC = vscode_lab_main.c

include $(APPDIR)/Application.mk
